# Generated by Django 3.1.1 on 2020-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Assignment date'),
        ),
    ]
